
subdirs = [
  'lang',
  'concurrent',
  'network',
  'system',
  'data',
  'math',
  'text',
  ]

def options(opt):
  opt.recurse('network')

def configure(conf):
  conf.check_cxx(lib = 'pthread')

  conf.recurse(subdirs)

def build(bld):
  b = bld.shlib(
    source = 'empty.cpp',
    target = 'pficommon',
    vnum = bld.env['VERSION'],
    use = [
      'pficommon_concurrent',
      'pficommon_data',
      'pficommon_lang',
      'pficommon_math',
      'pficommon_network',
      'pficommon_system',
      'pficommon_text',
      ])

  bld.recurse(subdirs)
